### ISSUE TITLE
AggregateException: Collection Was Modified

### ISSUE THREAD

**Issue by wgtmpeters** [eventflow/EventFlow#444]
Hi,

We are trying to setup a test that in parallel will trigger updates on the same aggregate roots.
This will obviously give a number a OptimisticConcurrency retries which is fine.
But sometimes we also see the following stack trace:
stem.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.) ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EventFlow.EventStores.EventStoreBase.<LoadEventsAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateRoot`2.<LoadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateStore.<LoadAsync>d__8`2.MoveNext() in C:\projects\eventflow\Source\EventFlow\Aggregates\AggregateStore.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass10_0`3.<<UpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Core.TransientFaultHandler`1.<TryAsync>d__5`1.MoveNext() in C:\projects\eventflow\Source\EventFlow\Core\TransientFaultHandler.cs:line 103

I am making starting the process by calling the aggregateStore.UpdateAsync in multiple threads, which have there own instance resolved.
The only thing that is shared should then be the InMemoryEventStore, could that be the issue here?

**Comment by rasmus** [comment]
@frankebersoll thanks, its easter holidays and I haven't been coding
