### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by ppumkin** [eventflow/EventFlow#472]
Yes.. that amazing .NET message we all love.

_Just background from me. I am a seasoned C# Dev but I am learning CQRS (and DDD) and first time using EventFlow - I am a complete newbie and zero exposure to any of this so fresh eyes_ 

This is an exception handling issue caused by a small mistake. I am using the `EventFlow.Examples.Shipping` project as the base for my project.

To reproduce:

`EventFlow.Examples.Shipping.Domain.Model.CargoModel.CargoAggregate.cs`

line 33
`private readonly CargoState _state = new CargoState();`

in my project i had 

`private readonly CustomerState _state; ` ~~= new CustomerState()~~

I missed the inline initialisation of the state object and the error just hardly made any sense.

stack trace

**"Object reference not set to an instance of an object."**

```
   at EventFlow.Aggregates.AggregateRoot`2.<>c__DisplayClass27_0.<ApplyEvent>b__0(IEventApplier`2 ea)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at EventFlow.Aggregates.AggregateRoot`2.ApplyEvent(IAggregateEvent`2 aggregateEvent)
   at EventFlow.Aggregates.AggregateRoot`2.Emit[TEvent](TEvent aggregateEvent, IMetadata metadata)
   at .Domain.Model.ExampleModel.ExampleAggregate.CreateCustomer(Customer customer) in C:\Code\.Lei.Domain\Model\ExampleModel\ExampleAggregate.cs:line 34
   at Domain.Model.ExampleModel.CommandHandlers.CreateCustomerCommandHandler.ExecuteCommandAsync(ExampleAggregate aggregate, CreateCustomerCommand command, CancellationToken cancellationToken) in C:\Code\Domain\Model\ExampleModel\CommandHandlers\CreateCustomerCommandHandler.cs:line 21
   at lambda_method(Closure , ICommandHandler , IAggregateRoot , ICommand , CancellationToken )
   at EventFlow.CommandBus.<>c__DisplayClass6_0`3.<ExecuteCommandAsync>b__1(TAggregate a, CancellationToken c)
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass10_0`3.<<UpdateAsync>b__0>d.MoveNext()

```

The problem is at this lovely nested line of code: ApplyEvent Line 183 AggregateRoot.cs in EventFlow project.

```
 else if (_eventAppliers.Any(ea => ea.Apply((TAggregate) this, aggregateEvent)))
```
the `ea.Apply` - That is the where the **Null Reference** is thrown

Don't know if its the nature of all this DDD or complexity of events but maybe some kind of check can be added to make sure this stupid and annoying .NET message does not get thrown (Microsoft did promise to make this message better years ago.... still causes lots of wasted time till today)

**Comment by rasmus** [comment]
Hi @ppumkin if you didn't initialize the state field, then the problem is that you are registering a null value for state.

![image](https://user-images.githubusercontent.com/18956/41055326-404890ea-69c1-11e8-9ff7-d32c94aeea91.png)

Maybe the `AggregateRoot<,,>.Register(...)` should throw an `ArgumentNullException` to helpout.

**Comment by rasmus** [comment]
I'll mark it as a question and create a PR that validates the arguments. Let me know if you disagree.

**Comment by ppumkin** [comment]
Excellent 🥇

**Comment by rasmus** [comment]
Released
