### ISSUE TITLE
Exception when using EventStores.EventStore hosted in aspnet.core (linux) on docker 

### ISSUE THREAD

**Issue by TorMartin74** [eventflow/EventFlow#524]
```
11:28:13:799 [Debug]: Execution of command 'CreateConfigurationCommand' with ID 'command-0e9384ac-804f-4d94-9075-fe7e8490e910' on aggregate 'ConfigurationDomain.ConfigurationAggregate' failed due to exception 'ObjectDisposedException' with message: Cannot access a disposed object.
Object name: 'EventFlow v0.64.3598.0'. - System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EventFlow v0.64.3598.0'.
   at EventFlow.EventStores.EventStore.EventStoreEventPersistence.LoadCommittedEventsAsync(IIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken)
   at EventFlow.EventStores.EventStoreBase.LoadEventsAsync[TAggregate,TIdentity](TIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateRoot`2.LoadAsync(IEventStore eventStore, ISnapshotStore snapshotStore, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateStore.LoadAsync[TAggregate,TIdentity](TIdentity id, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass10_0`3.<<UpdateAsync>b__0>d.MoveNext()
```

**Comment by rasmus** [comment]
@TorMartin74 I'm having a hard time reproducing the problem. Could you share some details about which object that throws the exception.

Have a look at the test in #525 here https://github.com/eventflow/EventFlow/pull/525/files#diff-a960ceab79a6fff3052f97f2415e1303R300

**Comment by wernert72** [comment]
Not sure if it is related but i have the same issue only in [UpdateAsync](https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/Aggregates/AggregateStore.cs).
It happends when trying to resolve IDomainEventPublisher in my case.
Maybe [this so thread](https://stackoverflow.com/questions/51169733/net-core-2-1-objectdisposedexception-cannot-access-a-disposed-object-object) is related ?

I'm using DependencyInjection Pckg running latest version of .net core.
In my case no docker and on windows.

**Comment by TorMartin74** [comment]
Some details:
I had Eventstore hosted in a docker container and an aspnet.core app hosted in another docker cointainer and using .UseEventStoreEventStore(uri), this exception was thrown when eventflow was loading events.

It worked fine when the asp.net core Application was executed outside docker.

Sidenote:
I got it working by using ConnectionSettings...

**Comment by TorMartin74** [comment]
@rasmus Yes, that is correct

**Comment by rasmus** [comment]
Ok, thanks

**Comment by RTodorov** [comment]
@rasmus I ran into this as well and the easiest way I found to reproduce it is:

- `docker-compose up -d` with EventStore on it, exposing the ports 1113 and 2113
- `dotnet run` on local machine with EventStore URL set to `tcp://localhost:1113`
- Trigger an event in the application
- `docker-compose down`
- Trigget another event in the application
- boom

hope that helps.

Some info about my environment:

- DependencyInjection 
- .NET Core 2.1 on MacOS
- EventFlow 0.69.3772

**Comment by rasmus** [comment]
@RTodorov Just to be sure. You have EventFlow in another instance and when you shutdown EventStore, the EventStore integration dies?

**Comment by RTodorov** [comment]
@rasmus I run both on the same local Mac, EventStore is ran via docker-compose and Eventflow is ran via `dotnet run` outside of docker.

Here's my docker-compose file:

```
version: '3.6'
services:
    eventstore:
        image: eventstore/eventstore
        restart: unless-stopped
        ports:
            - "1113:1113"
            - "2113:2113"
```

Full stacktrace if that helps:

```[17:07:15 DBG] Execution of command 'AskQuestionCommand' with ID 'command-665094a5-f742-46e5-a1e2-bb348cfe6cb3' on aggregate 'AskMe.Domain.Aggregates.QuestionAggregate' failed due to exception 'ObjectDisposedException' with message: Cannot access a disposed object.
Object name: 'EventFlow v0.69.3772.0'.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EventFlow v0.69.3772.0'.
   at EventFlow.EventStores.EventStore.EventStoreEventPersistence.LoadCommittedEventsAsync(IIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken)
   at EventFlow.EventStores.EventStoreBase.LoadEventsAsync[TAggregate,TIdentity](TIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/EventStores/EventStoreBase.cs:line 155
   at EventFlow.Aggregates.AggregateRoot`2.LoadAsync(IEventStore eventStore, ISnapshotStore snapshotStore, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateRoot.cs:line 115
   at EventFlow.Aggregates.AggregateStore.LoadAsync[TAggregate,TIdentity](TIdentity id, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 79
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass11_0`3.<<UpdateAsync>b__0>d.MoveNext() in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at EventFlow.Core.TransientFaultHandler`1.TryAsync[T](Func`2 action, Label label, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Core/TransientFaultHandler.cs:line 88
   at EventFlow.Aggregates.AggregateStore.UpdateAsync[TAggregate,TIdentity,TExecutionResult](TIdentity id, ISourceId sourceId, Func`3 updateAggregate, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 114
   at EventFlow.CommandBus.ExecuteCommandAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/CommandBus.cs:line 138
   at EventFlow.CommandBus.PublishAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/CommandBus.cs:line 74
[17:07:15 ERR] Connection id "0HLLHAJQA3ENI", Request id "0HLLHAJQA3ENI:00000001": An unhandled exception was thrown by the application.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EventFlow v0.69.3772.0'.
   at EventFlow.EventStores.EventStore.EventStoreEventPersistence.LoadCommittedEventsAsync(IIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken)
   at EventFlow.EventStores.EventStoreBase.LoadEventsAsync[TAggregate,TIdentity](TIdentity id, Int32 fromEventSequenceNumber, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/EventStores/EventStoreBase.cs:line 155
   at EventFlow.Aggregates.AggregateRoot`2.LoadAsync(IEventStore eventStore, ISnapshotStore snapshotStore, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateRoot.cs:line 115
   at EventFlow.Aggregates.AggregateStore.LoadAsync[TAggregate,TIdentity](TIdentity id, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 79
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass11_0`3.<<UpdateAsync>b__0>d.MoveNext() in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at EventFlow.Core.TransientFaultHandler`1.TryAsync[T](Func`2 action, Label label, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Core/TransientFaultHandler.cs:line 88
   at EventFlow.Aggregates.AggregateStore.UpdateAsync[TAggregate,TIdentity,TExecutionResult](TIdentity id, ISourceId sourceId, Func`3 updateAggregate, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/Aggregates/AggregateStore.cs:line 114
   at EventFlow.CommandBus.ExecuteCommandAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/CommandBus.cs:line 138
   at EventFlow.CommandBus.PublishAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken) in /Users/renato.todorov/Projects/EventFlow/Source/EventFlow/CommandBus.cs:line 74
   at EventFlow.CommandBusExtensions.PublishAsync[TAggregate,TIdentity,TResult](ICommandBus commandBus, ICommand`3 command) in /Users/renato.todorov/Projects/STACK/src/AskMe.Api/CommandBusExtensions.cs:line 17
   at AskMe.Api.Controllers.QuestionsController.Ask(NewQuestionInput input) in /Users/renato.todorov/Projects/STACK/src/AskMe.Api/Controllers/QuestionsController.cs:line 55
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by 7thcubic** [comment]
Not sure if it is related but.

Unless you pass a database option with --db, Event Store writes to a new database created in the host system's temporary files path each time it is started. For more information on Command Line Arguments read this guide.

I have read that eventstore docker is for testing/development only?

**Comment by bklooste** [comment]
Same issue with VS 2019 preview which has docker debugging now , so its going to get more common..   I have a pretty bare bone demo , with almost no IOC ( Its evil)  , if its needed https://github.com/bklooste/cqrs-simple-micro-service ( logic service only)  .

7thcubic  It happens when connecting FROM a docker container running .net core . It does not matter if event store is docker hosted or not.

**Comment by bklooste** [comment]
Ok solved it for me for anyone else that has this.

You cant use localhost or 127.0.0.1 from the docker container as that stays on the container not back to the host.

In terms of object disposed thats an artifact of IOC hiding things  ;-( 

I  put a read of 1 record in startup and it became pretty obvious.

**Comment by rasmus** [comment]
Solution found
