### ISSUE TITLE
Emit in aggregate leads to null id error

### ISSUE THREAD

**Issue by FinalFortune** [eventflow/EventFlow#698]
I have a simple Create command for my aggregate and was hoping someone could give me a lead as to what can cause the following error:

the Id at the time is:

    this.id = "event-daf6ba08-b5e6-4865-b96f-c5c514ef285d"

### Identity class
```
    public class EventId : Identity<EventId>
    {
        public EventId(string id) : base(id) { }
    }
```

### Emit Operation

```
        public IExecutionResult CreateEvent(DateTimeOffset startTime, string description, Alarm.Alarm alarm, DateTimeOffset? endTime)
        {
            Emit(new EventCreatedEvent(new EventEntity(this.Id)
            {
                Description = description,
                StartTime = startTime,
                Alarm = alarm,
                EndTime = endTime
            }));

            return ExecutionResult.Success();
        }
```

### Entity with Id
```
    public class EventEntity : Entity<EventId>
    {
        public EventEntity(EventId id) : base(id) { }
        public string Description { get; set; }
        public DateTimeOffset StartTime { get; set; }
        public DateTimeOffset? EndTime { get; set; }
        public Alarm.Alarm Alarm { get; set; }
    }
```
### Event
```
    public class EventCreatedEvent : AggregateEvent<EventAggregate, Domain.Events.EventId>
    {
        public EventEntity Event { get; }

        public EventCreatedEvent(EventEntity eventEntity)
        {
            Event = eventEntity;
        }
    }

```
### Error
```
System.ArgumentException: Identity is invalid: Identity of type 'EventId' is null or empty
   at EventFlow.Core.Identity`1..ctor(String value) in [redacted]\Source\EventFlow\Core\Identity.cs:line 119
   at [redacted].Domain.Events.EventId..ctor(String id) in [redacted]\Event\EventId.cs:line 7
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at EventFlow.EventStores.EventJsonSerializer.Deserialize(String aggregateId, String json, IMetadata metadata) in C:\projects\eventflow\Source\EventFlow\EventStores\EventJsonSerializer.cs:line 108
   at EventFlow.EventStores.EventJsonSerializer.Deserialize[TAggregate,TIdentity](TIdentity id, ICommittedDomainEvent committedDomainEvent) in C:\projects\eventflow\Source\EventFlow\EventStores\EventJsonSerializer.cs:line 99
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EventFlow.EventStores.EventStoreBase.StoreAsync[TAggregate,TIdentity](TIdentity id, IReadOnlyCollection`1 uncommittedDomainEvents, ISourceId sourceId, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateRoot`2.CommitAsync(IEventStore eventStore, ISnapshotStore snapshotStore, ISourceId sourceId, CancellationToken cancellationToken)
   at EventFlow.Snapshots.SnapshotAggregateRoot`3.CommitAsync(IEventStore eventStore, ISnapshotStore snapshotStore, ISourceId sourceId, CancellationToken cancellationToken) in C:\projects\eventflow\Source\EventFlow\Snapshots\SnapshotAggregateRoot.cs:line 89
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass11_0`3.<<UpdateAsync>b__0>d.MoveNext() in C:\projects\eventflow\Source\EventFlow\Aggregates\AggregateStore.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at EventFlow.Core.TransientFaultHandler`1.TryAsync[T](Func`2 action, Label label, CancellationToken cancellationToken)
   at EventFlow.Aggregates.AggregateStore.UpdateAsync[TAggregate,TIdentity,TExecutionResult](TIdentity id, ISourceId sourceId, Func`3 updateAggregate, CancellationToken cancellationToken)
   at EventFlow.CommandBus.ExecuteCommandAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken) in C:\projects\eventflow\Source\EventFlow\CommandBus.cs:line 138
   at EventFlow.CommandBus.PublishAsync[TAggregate,TIdentity,TResult](ICommand`3 command, CancellationToken cancellationToken)
   at Event.ReadStore.Services.EventCommandService.CreateEventAsync(DateTimeOffset startTime, String description, Nullable`1 endTime, CancellationToken ct) in [redacted]\Source\MicroServices\Event\Event.ReadStore\Services\EventCommandService.cs:line 27
   at Event.Service.Controllers.EventController.AddEvent(EventViewModel viewModel, CancellationToken ct) in [redacted]\Event.Service\Controllers\EventController.cs:line 46
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by FinalFortune** [comment]
It seems after the JSON serialization section the id is null

```
            var domainEvents = committedDomainEvents
                .Select(e => _eventJsonSerializer.Deserialize<TAggregate, TIdentity>(id, e))
                .ToList();
```

My application is mostly the same structure as @MongkonEiadon's VehicleTracker example.
However, I am using EventStore and not using the EntityFramework Event/Snapshot store implementations.
```
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            var env = EnvironmentConfiguration.Bind(_configuration);

            services
                .AddAutoMapper(typeof(EventMapperProfile).Assembly)
                .AddSingleton(env)
                .AddSwaggerGen(c => c.SwaggerDoc("v1", new Swashbuckle.AspNetCore.Swagger.Info { Title = "Events API", Version = "v1" }))
                .AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            return EventFlowOptions.New
                .UseServiceCollection(services)
                .AddAspNetCore()
                .UseConsoleLog()
                .UseEventStoreEventStore(new Uri(env.EventStoreConnection))
                .RegisterModule<DomainModule>()
                .RegisterModule<EventReadStoreModule>()
                .PublishToRabbitMq(RabbitMqConfiguration.With(new Uri(env.RabbitMqConnection)))
                .CreateServiceProvider();
        }
```

Still not sure what causes it to fail JSON conversion or set the Id to null

**Comment by rasmus** [comment]
I'll have a look, on holiday now but will do it asap.

**Comment by FinalFortune** [comment]
I added `[JsonConverter(typeof(SingleValueObjectConverter))]` to

``` c#
public class EventId : Identity<EventId>
{
    public EventId(string id) : base(id) { }
}
```

And it seems to deserialize successfully
as the Id is stored with a key name of "Value" in the JSON object without the _JsonConverter_ attribute.

**Comment by rasmus** [comment]
Seems to be fixed by using the correct attribute
