### ISSUE TITLE
No versioned type definition for 'ItemCreated' with version 1 in 'EventDefinitionService'

### ISSUE THREAD

**Issue by FinalFortune** [eventflow/EventFlow#762]
I have a separate application using the Async subscription to the event, And I get this when it tries deserialize.

```
at EventFlow.Core.VersionedTypes.VersionedTypeDefinitionService`3.GetDefinition(String name, Int32 version)
   at EventFlow.EventStores.EventJsonSerializer.Deserialize(String aggregateId, String json, IMetadata metadata)
   at EventFlow.EventStores.EventJsonSerializer.Deserialize(String json, IMetadata metadata)
   at EventFlowRmqConsumerHandler.HandleAsync(Object sender, BasicDeliverEventArgs args, CancellationToken cancellationToken)
   at LoggedEventFlowRmqConsumerHandler.HandleAsync(Object sender, BasicDeliverEventArgs args, CancellationToken cancellationToken)
   at LoggedEventFlowRmqConsumerHandler.HandleAsync(Object sender, BasicDeliverEventArgs args, CancellationToken cancellationToken)
```

the event is marked with the EventVersion attribute.
```
    [EventVersion("ItemCreated", 1)]
    public class ItemCreatedEvent : AggregateEvent<ItemAggregate,ItemId>
    { ... }
```
and i have
```
eventFlowOptions.AddAsynchronousSubscriber<ItemAggregate, ItemId, ItemCreatedEvent, ItemCreatedEventHandler>();
```

What exactly do I need to ensure the event ends up in the definition service?

**Comment by FinalFortune** [comment]
closing, related to #737
